export default {
  name: `settingsCompany`,
  title: `Settings - Company Information`,
  type: `document`,
  // __experimental_actions: [/*'create',*/ 'update', /*'delete',*/ 'publish'],
  fields: [
    {
      name: `name`,
      title: `Company: Name`,
      description: `Add the name of the company. Example: "John Grattan SEO & Web Design" `,
      type: `string`,
      initialValue: `John Grattan SEO & Web Design`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `website`,
      title: `Company: Website URL`,
      description: `Add the URL of the company's website. Example: "https://johngrattan.com" `,
      type: `string`,
      initialValue: `https://johngrattan.com`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `owner`,
      title: `Company: Owner`,
      description: `Add the owner of the company. Example: "John Grattan"`,
      type: `string`,
      initialValue: `John Grattan`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `phone`,
      title: `Company: Phone Number`,
      description: `Add the company's phone number. Example: "(401) 216-9868"`,
      type: `string`,
      initialValue: `(401) 216-9868`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `phoneHref`,
      title: `Company: Phone Number (Href)`,
      description: `Add the company's phone number. Example: "tel:+14012169868"`,
      type: `string`,
      initialValue: `tel:+14012169868`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `email`,
      title: `Company: Email Address`,
      description: `Add the company's email address. Example: "contact@johngrattan.com"`,
      type: `string`,
      initialValue: `contact@johngrattan.com`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `emailHref`,
      title: `Company: Email Address (Href)`,
      description: `Add the company's email address. Example: "mailto:contact@johngrattan.com?Subject=Important%20Email%20From%20Website"`,
      type: `string`,
      initialValue: `mailto:contact@johngrattan.com?Subject=Important%20Email%20From%20Website`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `address`,
      title: `Company: Physical Address`,
      description: `Add the company's physical address. Example: "30 Roosevelt Rd, Plymouth, MA 02360"`,
      type: `string`,
      initialValue: `30 Roosevelt Rd, Plymouth, MA 02360`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `street`,
      title: `Company: Street`,
      description: `Add the company's street. Example: "30 Roosevelt Rd"`,
      type: `string`,
      initialValue: `30 Roosevelt Rd`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `cityState`,
      title: `Company: City, State`,
      description: `Add the company's city and state. Example: "Plymouth, MA"`,
      type: `string`,
      initialValue: `Plymouth, MA`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `zip`,
      title: `Company: Zip Code`,
      description: `Add the company's zip code. Example: "02360"`,
      type: `string`,
      initialValue: `02360`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `hours`,
      title: `Company: Hours`,
      description: `Add the company's hours of operation. Example: "Mon-Sat: 7AM-5PM; Sun: 10AM-5PM"`,
      type: `string`,
      initialValue: `Mon-Sat: 7AM-5PM; Sun: 10AM-5PM`,
      // validation: (Rule) => Rule.required(),
    },
  ],
};
